### ISSUE TITLE
Hardly to show the comments in code diff

### ISSUE THREAD

**Issue by nullmax** [smashedtoatoms/zenburn#5]
IntelliJ IDEA 2023.2.1 (Ultimate Edition)
macOS Ventura 13.4.1

In code diff
![image](https://github.com/smashedtoatoms/zenburn/assets/11457071/d88afee1-ff8d-47d4-ac85-59dbfeedbbff)

In editor 
![image](https://github.com/smashedtoatoms/zenburn/assets/11457071/01a74186-bea8-42d2-bcaf-955c611e9c1b)

**Comment by smashedtoatoms** [comment]
Oooh, that's gnarly.  I'll try to figure out what I borked on that and get it updated asap.

**Comment by smashedtoatoms** [comment]
This should now be fixed by this commit: f92ef92c84941f90573cf3f77d08d12db03be9cf.  It usually takes ~24 hours to get approval, at which point it will become available to be updated.  If you want to update it manually before then, you can install it from here https://plugins.jetbrains.com/plugin/17938-zenburn/versions/stable/393485.  If this works, please let me know.  If I haven't heard back in the next day or two, I will close it.  Sorry for the inconvenience.  Thanks for letting me know!

**Comment by nullmax** [comment]
much better now 👍🏻

![image](https://github.com/smashedtoatoms/zenburn/assets/11457071/1686921f-6029-4687-a93f-0a03a69f143c)

**Comment by smashedtoatoms** [comment]
Cool!  Thanks for checking it so quickly.  That makes my life a lot easier to keep organized!
