### ISSUE TITLE
IntelliJ IDEA 2023.3 (Community Edition) says Zenburn plugin is incompatible

### ISSUE THREAD

**Issue by ikr** [smashedtoatoms/zenburn#7]
After I updated IntelliJ, Zenburn was disabled as incompatible. Now I don't see it at all in the Marketplace.

**Comment by smashedtoatoms** [comment]
Ok, I haven't upgraded yet so I'm sure they're going to make me update the entire thing and republish it because god forbid we preserve backwards compatibility between releases. 

I'm not going to be able to fix this until tonight but I'll try to get it fixed and published tonight and let you know once I've done it. Sorry for the inconvenience.

**Comment by ikr** [comment]
Take your time, no pressure at all! So nice of you! <3 Thanks a bunch!

**Comment by smashedtoatoms** [comment]
Here is the updated version. You can download and install it directly if you don't want to wait for it to get through the JetBrains approval process.  It takes about 24 hours to get through, at which point it will show up in the market again.  I'm really sorry.  This regularly falls through the cracks with me.

https://plugins.jetbrains.com/plugin/17938-zenburn/versions/stable/451169

**Comment by ikr** [comment]
Lovely! Thank you again!
